s = input("Enter a string: ")
# print(s.lower())
# print(s.upper())
# print(s.title())
# print(s.swapcase())
# print(s.startswith('p'))
# print(s.endswith('n'))
# print(s.split())
# print(s.join('la'))
# print(s.index('p'))
# print(s.count('p'))
# print(s.capitalize())